---
title: KLASS
timezone: Asia/Tashkent
collections:
  posts:
    title: Posts
    output: true
  detskie:
    title: Детские
    output: true
permalink: "/:categories/:year/:month/:day/:title/:name"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
highlighter: 
markdown: kramdown
extensions:
- fenced_code_blocks
excerpt_separator: "<!--more-->"
url: https://alpenuga.github.io
baseurl: "/alpenuga.github.io"
data-ad-slot: 
data-ad-client: 
google_ad_client: 
post_limit: 5
tagline: bolajon furniture
author:
  name: Klass
  site: https://alpenuga.github.io
  description: Мебель для детской, диваны, столы и стулья, мебель на заказ.
  image: IMGN.png
  email: shop@eklass.ml
  github: alpenuga
  twitter: 
  facebook: klass.uz
  linkedin: 
  instagram: klassbolajon
  pinterest: 
  feedburner: 
twitter_username: 
production_url: https://alpenuga.github.io
JB:
  version: 0.3.0
  BASE_PATH: https://alpenuga.github.io
  ASSET_PATH: https://alpenuga.github.io/assets/themes/bootstrap
  archive_path: "/archive.html"
  categories_path: "/categories.html"
  tags_path: "/tags.html"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  comments:
    provider: facebook
    facebook:
      short_name: klass.uz
      num_posts: 5
      width: 580
      colorscheme: light
  analytics:
    provider: google
    google:
      tracking_id: 
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
    piwik:
      baseURL: myserver.tld/piwik
      idsite: 1
  sharing:
    provider: false
